### ISSUE TITLE
HTML.Index Best Practices and Indentation 

### ISSUE THREAD

**Issue by Cili23** [Cili23/content-semantics#1]
@hellachella
@carolsinc

I seem to be having a indentation issue throughout my HTML.Index file.
<img width="361" alt="Screen Shot 2021-02-12 at 14 16 59 PM" src="https://user-images.githubusercontent.com/77252057/107811999-0e94d680-6d3d-11eb-989d-9329517283af.png">

**Comment by hellachella** [comment]
Was this resolved? I know we talked about it in class.

**Comment by hellachella** [comment]
You should be able to just use auto indent.

**Comment by Cili23** [comment]
This was resolved. Its somehow fixed itself.
